"""empty message

Revision ID: 3168a1a4a587
Revises: 
Create Date: 2022-12-27 03:41:27.781845

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3168a1a4a587"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "comic",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("comic")
    # ### end Alembic commands ###
